version: "3.3"
services:
  backend:
    # docker-composeファイルと同階層のDockerfileをビルド
    build: .
    ports:
      # ローカル:docker
      - 9999:3333
        # docker とローカルの FS をマウント
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:5.7
      # restart: always
    environment:
      MYSQL_DATABASE: note
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
    # ローカルに .database を作成し、dbコンテナとFSをマウント
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - .database:/var/lib/mysql
    ports:
      - 33696:3306

